# Week 2 Day Lab

### Problem 1: Installing NumPy

If not already installed, install the numpy library using `!pip install numpy`. After installing, import numpy with variable name `np`.

In [2]:
import numpy as np

### Problem 2: Installing other libraries
We will use other libraries throughout this semester as well. Here are a couple:

    - matplotlib
    - networkx
    - pandas
    - geopandas
Try importing these libraries. If they are not installed, use `pip install` to install them for future use.

In [5]:
import matplotlib

import networkx

import pandas

import geopandas

### Problem 3

Given

```python
a = np.array([2, 4, 6, 8])
```

compute each of the following:

1. a + 3
2. 2 * a
3. a**2
4. a - 1

Do not use a `for` loop.


In [7]:
a = np.array([2, 4, 6, 8])

print(a + 3)
print(2 * a)
print(a**2)
print(a - 1)

[ 5  7  9 11]
[ 4  8 12 16]
[ 4 16 36 64]
[1 3 5 7]


### Problem 4

The derivative of a function \(f(x)\) at a point \(x\) is defined as the limit

$
f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}
$

provided the limit exists.

Define a function $g(h)$ that computes the quotient above for a given function $f$ near a point $x$. Then, vectorize $g$. 


Using `np.linspace()`, let $f(x)=sin(x)$ and compute $g$ at $10^{-1}, 10^{-2}, 10^{-3}, 10^{-4}$. This will be an estimate for the derivative of $f$. Compare to the actual derivative.

In [12]:
import numpy as np

def f(x):
    return np.sin(x)

x = 1
def g(h):
    return (f(x + h) - f(x)) / h

g = np.vectorize(g)

h = np.linspace(1e-1, 1e-4, 4)

print('h values')
print(h)

print('difference quotient estimates')
print(g(h))

print('derivative')
print(np.cos(x))

h values
[0.1    0.0667 0.0334 0.0001]
difference quotient estimates
[0.49736375 0.51184912 0.5261506  0.54026023]
derivatives
0.5403023058681398


###  Problem 5
Let

$
A=
\begin{bmatrix}
2 & 1 \\
3 & 4
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
5 & 2 \\
1 & 6
\end{bmatrix}
$

Compute the product.

In [11]:
import numpy as np

A = np.array([[2, 1],
              [3,4]])

B = np.array([[5, 2],
              [1,6]])

print(A@B)


[[11 10]
 [19 30]]
